Appman 791 initial call to get nhs data
SkillsFundingAgency/das-public-sector-organisations-api pull request #3
Opened 2024-03-19 10:17 UTC by Pauljgraham

This is just to populate the data

2024-03-27 10:25 UTC, cofaulco approved these changes

2024-03-27 10:25 UTC, cofaulco commented on src/SFA.DAS. PublicSectorOrganisations.Api/Controllers/PublicSectorOrganisationsController.cs
> +    [Route("/PublicSectorOrganisations")]
use `[controller]`

2024-03-27 10:25 UTC, cofaulco commented on src/SFA.DAS. PublicSectorOrganisations.Api/appsettings.Development.json
> +  "PublicSectorOrganisationsConfiguration": {
should this config be in table storage as opposed to appsettings?

2024-03-27 10:25 UTC, cofaulco commented on src/SFA.DAS.PublicSectorOrganisations.Api.Tests/Controllers/PublicSectorOrganisations/WhenCallingGetPublicSectorOrganisationById.cs
> +
remove blank line

2024-03-27 10:25 UTC, cofaulco commented on src/SFA.DAS.PublicSectorOrganisations.Application/Commands/Import/ImportCommandHandler.cs
> +    private readonly IOnsImporterService _onsImporterService;
could have them all implement a single interface and register them all and inject IEnumerable<IPublicSectorDataImporterService> or something of the like

2024-03-27 10:25 UTC, cofaulco commented on src/SFA.DAS.PublicSectorOrganisations.Data.Tests/Ons/OnsDownloadService/WhenCreatingExcelFileFromDownload.cs
> +
blanks

2024-03-27 10:25 UTC, cofaulco commented on src/SFA.DAS.PublicSectorOrganisations.Data.Tests/Ons/OnsDownloadService/WhenCreatingExcelFileFromDownload.cs
> +        filePath.EndsWith("publicsectorclassificationguidelatest").Should().BeTrue();
double blanks

2024-03-27 10:25 UTC, cofaulco requested changes
a few minor issues

2024-03-27 17:12 UTC, Pauljgraham commented on src/SFA.DAS. PublicSectorOrganisations.Api/appsettings.Development.json
> +  "PublicSectorOrganisationsConfiguration": {
I have a PR for the config 

https://github.com/SkillsFundingAgency/das-employer-config/pull/1826

but whilst it's not there I have to use this. I'm not 100% sure whether we should keep the appsettings.development.json because it sometimes contains private keys (but not in this repo). There should be an advantage that the config here should override the config file values if we wire it up in the appropriate order

2024-03-27 17:15 UTC, Pauljgraham commented on src/SFA.DAS.PublicSectorOrganisations.Application/Commands/Import/ImportCommandHandler.cs
> +    private readonly IOnsImporterService _onsImporterService;
Looking at that now, I wanted to do it that way, will chat about it tomorrow

2024-03-28 09:27 UTC, Pauljgraham commented on src/SFA.DAS.PublicSectorOrganisations.Application/Commands/Import/ImportCommandHandler.cs
> +    private readonly IOnsImporterService _onsImporterService;
much nicer implementation

2024-03-28 10:03 UTC, cofaulco submitted a review, later dismissed

2024-06-25 08:53 UTC, closed without merging