APPMAN-876 added ImportAudit table
SkillsFundingAgency/das-public-sector-organisations-api pull request #4
Opened 2024-04-03 14:51 UTC by Pauljgraham

2024-04-09 09:54 UTC, cofaulco approved these changes

2024-04-29 19:30 UTC, cofaulco approved these changes

2024-04-29 19:32 UTC, cofaulco requested changes

2024-04-29 19:32 UTC, cofaulco commented on src/SFA.DAS.PublicSectorOrganisations.Api/SFA.DAS.PublicSectorOrganisations.Api.csproj
> +    </ItemGroup>
can these be removed?

2024-04-30 13:35 UTC, cofaulco submitted a review, later dismissed

2024-06-11 14:24 UTC, cofaulco requested changes

2024-06-11 14:24 UTC, cofaulco commented on src/SFA.DAS.PublicSectorOrganisations.Data.Tests/Ons/OnsDownloadService/WhenCreatingExcelFileFromDownload.cs
> +            await sut.CreateLatestOnsExcelFile();
can we use ShouldThrow() here?

2024-06-11 14:24 UTC, cofaulco commented on src/SFA.DAS.PublicSectorOrganisations.Data.Tests/Ons/OnsExcelReaderServiceUsingClosedXml/WhenReadingAnExcelFile.cs
> +            Assert.Fail("Should reach here");
can we use ShouldThrow() here?

2024-06-11 14:24 UTC, cofaulco commented on src/SFA.DAS.PublicSectorOrganisations.Data/Ons/OnsExcelReaderService.cs
> +    public class OnsExcelReaderService(ILogger<OnsExcelReaderService> logger) : IOnsExcelReaderService
any need to keep this class now?

2024-06-11 15:23 UTC, Pauljgraham commented on src/SFA.DAS.PublicSectorOrganisations.Data/Ons/OnsExcelReaderService.cs
> +    public class OnsExcelReaderService(ILogger<OnsExcelReaderService> logger) : IOnsExcelReaderService
no removed

2024-06-12 07:49 UTC, cofaulco submitted a review, later dismissed

2024-06-25 08:36 UTC, cofaulco approved these changes

2024-06-25 08:41 UTC, furqanagwan approved these changes

2024-06-25 08:50 UTC, merged